name: <Native> Linter

on:
  push:

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: ClangTidy Android
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install CMake & Clang Tidy
        run: |
          sudo apt update
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8
          sudo update-alternatives --config python

          cd .github/workflows
          chmod +x ./llvm.sh
          sudo ./llvm.sh 11
          sudo apt update --fix-missing
          sudo apt install -y clang-tidy-11

